name: SpokyAI CI/CD Pipeline

on:
  push:
    branches: [ main, spokyai, develop ]
  pull_request:
    branches: [ main, spokyai ]

jobs:
  test:
    name: Test Python Scripts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f SpokyAI/requirements.txt ]; then
          pip install -r SpokyAI/requirements.txt
        fi
    
    - name: Lint with flake8
      run: |
        pip install flake8
        # Stop the build if there are Python syntax errors or undefined names
        flake8 SpokyAI/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 SpokyAI/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Check code formatting with black
      run: |
        pip install black
        black --check SpokyAI/ || true
    
    - name: Run tests with pytest
      run: |
        pip install pytest pytest-cov
        if [ -d SpokyAI/tests ]; then
          pytest SpokyAI/tests/ --cov=SpokyAI --cov-report=xml --cov-report=html || true
        fi
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: matrix.python-version == '3.10'
      with:
        file: ./coverage.xml
        flags: unittests
        fail_ci_if_error: false

  security:
    name: Security Checks
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Checkov for configuration validation
      uses: bridgecrewio/checkov-action@master
      with:
        directory: SpokyAI/config/
        framework: all
        output_format: cli
        soft_fail: true
    
    - name: Run Bandit security scan
      run: |
        pip install bandit
        bandit -r SpokyAI/ -f json -o bandit-report.json || true
    
    - name: Upload Bandit report
      uses: actions/upload-artifact@v3
      with:
        name: bandit-security-report
        path: bandit-report.json

  simulation:
    name: Installation Simulation
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Simulate Vosk installation
      run: |
        pip install vosk
        echo "Vosk installation successful"
    
    - name: Simulate PyTorch installation
      run: |
        pip install torch --index-url https://download.pytorch.org/whl/cpu
        echo "PyTorch installation successful"
    
    - name: Simulate pyautogui setup
      run: |
        pip install pyautogui
        echo "pyautogui installation successful"
    
    - name: Test voice agent setup simulation
      run: |
        echo "Voice agent setup simulation:"
        echo "1. Voice recognition module - Ready"
        echo "2. Audio input/output - Ready"
        echo "3. Command processing - Ready"
        echo "Installation simulation completed successfully"

  lambda-validation:
    name: Validate AWS Lambda Functions
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Lambda dependencies
      run: |
        pip install boto3 transformers pandas nltk
    
    - name: Validate Lambda syntax
      run: |
        python -m py_compile SpokyAI/lambda/data_storage.py
        python -m py_compile SpokyAI/lambda/data_processing.py
        python -m py_compile SpokyAI/lambda/sentiment_analysis.py
        python -m py_compile SpokyAI/lambda/rating_evaluation.py
        echo "All Lambda functions have valid syntax"
    
    - name: Check Lambda logging
      run: |
        echo "Checking for logging in Lambda functions..."
        grep -r "logger" SpokyAI/lambda/ && echo "Logging found in Lambda functions" || echo "Warning: No logging found"
